name: Release
runs:
  using: composite
  steps:
    - name: "Checkout"
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: "Release"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npm run semantic-release
