name: Deploy
description: Deploys to GitHub Pages
inputs:
  cname:
    description: Custom Domain
    required: true
  git-name:
    description: Git name
    required: true
  git-email:
    description: Git email
    required: true
  github-token:
    description: GitHub PAT
    required: true
  dry-run:
    description: Dry run
    default: "true"
runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
    - name: "Download all workflow run artifacts"
      uses: actions/download-artifact@v3
    - name: "Setup Node.js environment"
      uses: actions/setup-node@v3
      with:
        node-version: "18.x"
    - name: Install NPM dependencies
      shell: bash
      run: npm i
    - name: "Deploy website"
      if: ${{ inputs.dry-run == 'false' }}
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      run: |
        npx ng deploy --no-silent --branch=deploy --cname="${{ inputs.cname }}" --name="${{ inputs.git-name }}" --email="${{ inputs.git-email }}"
    - name: "Deploy website (dry-run)"
      if: ${{ inputs.dry-run == 'true' }}
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      run: |
        npx ng deploy --no-silent --dry-run --branch=deploy --cname="${{ inputs.cname }}" --name="${{ inputs.git-name }}" --email="${{ inputs.git-email }}"
