name: "GitHub Pages CI"
on:
  push:
    branches:
      - main
  pull_request:
env:
  ACTION: ${{ github.ref == 'refs/heads/main' && '(publish)' || '(dry-run)' }}

jobs:
  build:
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        uses: ./.github/actions/build
        with:
          google-analytics: ${{ secrets.GOOGLE_ANALYTICS }}

  deploy:
    name: "Deploy $ACTION"
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        uses: ./.github/actions/deploy
        with:
          cname: ${{ secrets.CUSTOM_DOMAIN }}
          git-name: ${{ secrets.GIT_NAME }}
          git-email: ${{ secrets.GIT_EMAIL }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          dry-run: ${{ github.ref != 'refs/heads/main' }} # dry-run if not on main branch

  release:
    name: "Release $ACTION"
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Release
        uses: ./.github/actions/release
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          dry-run: ${{ github.ref != 'refs/heads/main' }} # dry-run if not on main branch
