# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy my Angular website to GitHub Pages

on:
  push:
    branches: [ develop ]

jobs:
  deploy:
    -if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Node.js setup
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: Build
      run: npm ci
      run: npm run build:prod
     
