name: Pull request
on:
  pull_request:

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build
        with:
          google-analytics: ${{ secrets.GOOGLE_ANALYTICS }}

  deploy-dry-run:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/deploy
        with:
          cname: ${{ secrets.CUSTOM_DOMAIN }}
          git-name: ${{ secrets.GIT_NAME }}
          git-email: ${{ secrets.GIT_EMAIL }}
          dry-run: true

  release-dry-run:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/release
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          dry-run: true
