name: Pull request
on:
  pull_request:

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    !include jobs/build.yml

  release:
    needs: build
    !include jobs/release-dry-run.yml
