name: Pull request
on:
  pull_request:

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    uses: ./.github/actions/build.yml

  release:
    runs-on: ubuntu-latest
    needs: build
    uses: ./.github/actions/release-dry-run.yml
